version: 2
updates:
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - "jamf/opensource-regatta-write"
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-major"]
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - "jamf/opensource-regatta-write"
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - "jamf/opensource-regatta-write"
  groups:
    gomod:
      patterns:
      - "*"
  ignore:
  - dependency-name: "github.com/cockroachdb/pebble"
  - dependency-name: "github.com/armon/go-metrics"
  - dependency-name: "github.com/imdario/mergo"

